version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-development
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/bnb-network
    links:
      - mongo
    restart: always
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
