version: '2'

services:
  web:
    build: .
    volumes:
      - ./:/app
    links:
      - mongo
    restart: always
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
